name: auto-release

on:
  push:
    tags:
      - "v*.*.*"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Rename model directory
        run: mv models ${{github.ref_name}}
      - name: Archive models
        run: tar -czvf all_models-${{github.ref_name}}.tar.gz ${{github.ref_name}}
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            all_models-${{github.ref_name}}.tar.gz            
            LICENSE
